name: Sync blog content and Deploy Astro site

on:
  push:
    branches:
      - content-sync

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout content-sync branch
        uses: actions/checkout@v4
        with:
          ref: content-sync
          path: content-sync
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "kimstitute"
          git config --global user.email "kimstitute@naver.com"

      - name: Sync content into src/content/blog
        run: |
          mkdir -p src/content/blog
          rsync -av --delete --exclude '.git/' content-sync/ src/content/blog/

      - name: Commit and push changes (if any)
        run: |
          if git status --porcelain src/content/blog | grep -q .
          then
            git add src/content/blog
            git commit -m "chore: sync blog content from content-sync"
            git push origin main
          else
            echo "No content updates detected; skipping commit."
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
