name: Merge content-sync and Deploy Astro site

on:
  push:
    branches:
      - content-sync

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "kimstitute"
          git config --global user.email "kimstitute@naver.com"

      - name: Merge content-sync into main
        run: |
          echo "🔹 Fetching latest branches..."
          git fetch origin content-sync
          echo "🔹 Merging content-sync → main..."
          git merge origin/content-sync --allow-unrelated-histories -m "Auto-merge from content-sync"
          git push origin main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          echo "🔹 Installing dependencies..."
          npm ci
          echo "🔹 Building Astro site..."
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
